### ISSUE TITLE
Cannot select multiple items any more

### ISSUE THREAD

**Issue by LimpEmu** [HemantNegi/jquery.sumoselect#306] opened 2021-07-04 21:20 UTC
I updated sumoselect to the most recent version, however, now I can no longer select multiple options via JavaScript.

I save the options a user selected in a cookie as a comma separated string. When loading the page, I read the selections from the cookie. This worked fine with version 3.0.3 which BTW I am still using since the later versions have another bug related to option groups.

I am using the following syntax to load my options when a page is revisited:
```
   var cval = getCookie('ic_err');
   if (cval != "") {
     $.each(cval.split(","), function(i,e){
        $("#err option[value='" + e + "']").prop("selected", true);
     });
     setTimeout(function() {$('select.sumosel')[0].sumo.reload();},0);
```
I have tried changing to the syntax indicated on the sumoselect webpage (see below), making sure that sumoselect is loaded prior to loading the form settings, but that does not work either, 
```
   var cval = getCookie('ic_err');
   if (cval != "") {
     $.each(cval.split(","), function(i,e){
        $('select.sumosel')[0].sumo.selectItem(e); 
     });
```
In both cases, only the first option is selected, the others are ignored. I am going back to version 3.0.3 ....

I truly appreciate all your work on this multi-select, but I am disappointed that I try updating to the new versions to find that some important part that I am using no longer works. Thank you!

**Comment by Zenoo** [comment] 2021-07-04 21:21
Could you try to replicate the bug on a JSFiddle or Codepen?  
It seems to work on my end.

**Comment by LimpEmu** [comment] 2021-07-04 22:22
I don't have a CDN for sumoselect, so included the minimized version in the fiddle.

This fiddle is for 3.3.22
[JSFIDDLE Version 3.3.22](https://jsfiddle.net/limpemu/z1fets5w/4/)
Only 1 item is selected.

This fiddle is for 3.0.3
[JSFIDDLE Version 3.0.3](https://jsfiddle.net/limpemu/2cjqr58d/)
4 items are selected.

**Comment by Zenoo** [comment] 2021-07-05 06:46
Your fiddles were all running 3.3.22.  
Here is the one with 3.0.4: https://jsfiddle.net/Zenoo0/g497bvL0/
And here it is with 3.3.22: https://jsfiddle.net/Zenoo0/kwvmbxsz/

There is indeed a difference, I will check what the problem is.

**Comment by Zenoo** [comment] 2021-07-05 06:58
This should be fixed in [v3.3.23](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.23)

**Comment by LimpEmu** [comment] 2021-07-05 16:48
Thank you, sorry, i must have inserted the wrong fiddle link :/
I will test out the new version now!

**Comment by LimpEmu** [comment] 2021-07-05 16:58
Just tested it, now I get another error:
[JSFIDDLE with 3.3.23](https://jsfiddle.net/limpemu/2q3L68mn/3/)

```
"jQuery.Deferred exception: Cannot set property selectedOptions of #&lt;HTMLSelectElement&gt; which has only a getter", "TypeError: Cannot set property selectedOptions of #&lt;HTMLSelectElement&gt; which has only a getter
    at Object.createElems (https://fiddle.jshell.net/limpemu/2q3L68mn/3/show/?editor_console=:261:124)
    at Object.init (https://fiddle.jshell.net/limpemu/2q3L68mn/3/show/?editor_console=:318:95)
    at HTMLSelectElement.&lt;anonymous&gt; (https://fiddle.jshell.net/limpemu/2q3L68mn/3/show/?editor_console=:318:166)
    at Function.each (https://code.jquery.com/jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (https://code.jquery.com/jquery-3.6.0.min.js:2:1481)
    at S.fn.init.a.fn.SumoSelect (https://fiddle.jshell.net/limpemu/2q3L68mn/3/show/?editor_console=:254:10)
    at HTMLDocument.&lt;anonymous&gt; (https://fiddle.jshell.net/limpemu/2q3L68mn/3/show/?editor_console=:370:20)
    at e (https://code.jquery.com/jquery-3.6.0.min.js:2:30038)
    at t (https://code.jquery.com/jquery-3.6.0.min.js:2:30340)", undefined
"Uncaught TypeError: Cannot set property selectedOptions of #&lt;HTMLSelectElement&gt; which has only a getter"
```

**Comment by Zenoo** [comment] 2021-07-05 17:17
I will handle this bug in a few minutes, thanks for pointing it out

**Comment by Zenoo** [comment] 2021-07-05 17:35
This should be fixed in [v3.3.24](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.24).  
You talked about another bug with option groups, could you create another issue for this bug please?  
I'll gladly take a look at it.

**Closed** 2021-07-05 17:34 UTC
Labels: bug

**Comment by LimpEmu** [comment] 2021-07-05 18:00
Yes, that is the reason why I am using version 3.0.3, I modified your code based on information in https://github.com/HemantNegi/jquery.sumoselect/issues/227.

Let me check whether the updated version has the same bug, give me a moment.

**Comment by LimpEmu** [comment] 2021-07-05 18:06
I just checked with version 3.3.24. Both problems are fixed, the problem with the optgroups messing up the indices of the options and the problem of not being able to select multiple options.
THANK YOU!
