### ISSUE TITLE
Select All does not work in Safari

### ISSUE THREAD

**Issue by mariancerny** [HemantNegi/jquery.sumoselect#216] opened 2017-08-01 02:31 UTC
Select All does not work in Safari 10.11.1 on macOS 10.12.5 Sierra. It works in Chrome and Firefox on macOS.

**Comment by bhaiyyapatil** [comment] 2017-08-21 09:36
Same issue here. No patch is available right now. Please look into the issue.

**Comment by meterlongcat** [comment] 2017-09-27 06:23
I have the same problem in IE11. Did some digging and the cause for me was method `toggSelAll` where the line `O.E.find('option:not(:disabled,:hidden)')` returns an empty array in IE11. It looks like IE doesn't support multiple selectors in `not`, in fact this isn't meant to be supported until CSS4, see http://css4.rocks/negation-pseudo-class.php

I'm unsure if this is the same problem for Safari.

**Comment by jbinnig** [comment] 2020-08-13 17:34
I am using v3.0.3 and variety of browsers(IE 11, Edge). haven't tried chrome or firefox.
I tried with script as is, and with the aderayna's suggestion and still not working.

**Comment by Zenoo** [comment] 2021-06-20 15:29
This should be fixed in [v3.3.3](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.3)

**Closed** 2021-06-20 15:29 UTC
